#!/usr/bin/env bash
(cd node_modules/jalangi2/ && npm install)
(git clone https://github.com/ExpoSEJS/z3javascript.git node_modules/z3javascript && cd node_modules/z3javascript && sed -i'' -e 's/"node-gyp": "\*"/"node-gyp": "9.4.1"/' package.json && npm install)

